# Generated by Django 5.2.4 on 2025-08-02 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('brand_name', models.CharField(max_length=120, unique=True, verbose_name='Имя бренда')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Скидка в %')),
                ('description', models.TextField(verbose_name='Описане')),
                ('image', models.ImageField(upload_to='parfumes_images', verbose_name='Изображения')),
                ('quantity', models.PositiveBigIntegerField(default=0, verbose_name='Количество')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('ml_size', models.PositiveIntegerField(help_text='Size in millimiters')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='parfumes.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
                'ordering': ('-created_at',),
            },
        ),
    ]
