# Generated by Django 5.2.4 on 2025-08-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_ml', models.IntegerField(choices=[(10, '10ml'), (20, '20ml'), (30, '30ml'), (50, '50ml')])),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Цена для этого размера')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе для этого размера')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='parfumes.product')),
            ],
            options={
                'unique_together': {('product', 'size_ml')},
            },
        ),
    ]
