# Generated by Django 5.1.4 on 2025-08-22 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumes', '0002_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='parfumes.product', verbose_name='Имя'),
        ),
    ]
