# Generated by Django 5.2.4 on 2025-08-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumes', '0002_remove_product_ml_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(max_length=120, verbose_name='Имя бренда'),
        ),
    ]
