# Generated by Django 5.2.4 on 2025-08-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parfumes', '0003_alter_productvariant_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Вариант продукта', 'verbose_name_plural': 'Вариант продуктов'},
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size_ml',
            field=models.IntegerField(choices=[(10, '10ml'), (20, '20ml'), (30, '30ml'), (50, '50ml')], verbose_name='Объем (ml)'),
        ),
    ]
